name: Publish package to NPM

on:
  pull_request:
    branches:
      - dev
    types: closed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Storybook
      run: |
        yarn
        yarn publish:npm
