name: Publish package to NPM

on:
  pull_request:
    branches:
      - dev
    types: closed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ env.home}}/.npmrc
        contents: |
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        write-mode: append
    - name: Login NPM
      run: |
        npm whoami
    - name: Deploy Storybook
      run: |
        yarn
        yarn publish:npm
