name: Publish package to NPM

on:
  pull_request:
    branches:
      - dev
    types: closed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login NPM
      run: |
        npm whoami
        npm config set @myco:registry https://reg.example.com
        npm config set //reg.example.com/:_authToken ${{ secrets.NPM_TOKEN }}
        npm whoami
        # npm login --registry=https://reg.example.com --scope=@myco --token=b5d6626c-3ad2-43d4-95a7-0a11bc4b9d90
    - name: Deploy Storybook
      run: |
        yarn
        yarn publish:npm
